import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type React from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="app">
        <div className="flex h-full w-full">
          <div className="bg-gray-200 grow w-full"></div>
          <div className="flex h-screen max-w-[1024px] shrink-0 grow w-full flex-col">
            <AntdRegistry>{children}</AntdRegistry>
          </div>
          <div className="w-full"></div>
        </div>
      </body>
    </html>
  );
}
