import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type React from 'react';
import Header from './(layout)/Header';
import LeftNavigation from './(layout)/LeftNavigation';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="app">
        <div className='max-w-[1024px] mx-auto'>
          <AntdRegistry>
            <Header />
            <div className="flex p-5">
              <LeftNavigation />
              <div className="mx-auto mt-10 flex w-[500px] flex-col p-5">{children}</div>
            </div>
          </AntdRegistry>
        </div>
      </body>
    </html>
  );
}
