import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';
import type React from 'react';
import Link from 'next/link';
import Header from './(layout)/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="app">
        <Header />

        <AntdRegistry>
          <div className='flex p-5'>
            <menu className="flex flex-col basis-[200px]">
              <Link href="/home" className="hover:bg-blue-400 hover:text-white">
                Home
              </Link>
              <Link href="/deposit" className="hover:bg-blue-400 hover:text-white">Deposit funds</Link>
            </menu>
            <div className="mx-auto mt-10 flex w-[500px] flex-col p-5">{children}</div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
