import { createClient } from '@/utils/supabase/serverClient';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import type React from 'react';
import Header from '../(layout)/Header';
import LeftNavigation from '../(layout)/LeftNavigation';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return redirect('/login');
  }

  return (
    <>
      <Header />
      <div className="flex grow gap-5 pr-5">
        <div className="shrink-0 basis-[220px] bg-gray-200 pl-5">
          <LeftNavigation />
        </div>
        <div className="mt-5 flex grow flex-col">{children}</div>
      </div>
    </>
  );
}
