import type { Metadata } from 'next';
import type React from 'react';
import Header from '../(layout)/Header';
import LeftNavigation from '../(layout)/LeftNavigation';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="flex p-5">
        <LeftNavigation />
        <div className="mx-auto mt-10 flex w-[500px] flex-col p-5">
          {children}
        </div>
      </div>
    </>
  );
}
