import type { Metadata } from 'next';
import type React from 'react';
import Header from '../(layout)/Header';
import LeftNavigation from '../(layout)/LeftNavigation';
import '../globals.css';
import { createClient } from '@/utils/supabase/serverClient';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return redirect("/login");
  }

  return (
    <>
      <Header />
      <div className="flex p-5">
        <LeftNavigation />
        <div className="mx-auto mt-10 flex w-[500px] flex-col p-5">
          {children}
        </div>
      </div>
    </>
  );
}